turtlebot3: #namespace

    n_actions: 6 # We have 4 actions, Forwards,TurnLeft,TurnRight, Reverse

    speed_step: 1.0 # Time to wait in the reset phases

    linear_forward_speed: 0.22 # Speed for going fowards. Set to TB3 Max
    linear_turn_speed: 0.22 # Lienare speed when turning
    angular_speed: 0.25 # Angular speed when turning Left or Right
    init_linear_forward_speed: 0.0 # Initial linear speed in which we start each episode
    init_linear_turn_speed: 0.0 # Initial angular speed in shich we start each episode
    
    new_ranges: 25 # How many laser readings we jump in each observation reading, the bigger the less laser resolution
    min_range: 0.2 # Minimum meters below wich we consider we have crashed
    max_laser_value: 3.5 # Value considered Ok, no wall
    min_laser_value: 0 # Value considered there is an obstacle or crashed
    max_linear_aceleration: 5.0 # Linear acceleration value in which we consider Turtlebot 3 has crashed into something
    
    rewards:
        step: -1
        contact: -10
    

